
#General Config Section
[general]
	#The Client ID of the Discord App to use
	clientID = 901882268153413672
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 12
	updater = false

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Eterna | Currently is loading"
	#The second line of text under the app name
	state = "Eterna | Currently is Starting..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "eterna"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Eterna | https://www.curseforge.com/minecraft/modpacks/eterna-fabric"
	#The Asset ID of the image to display as the small image
	smallImageKey = "cube"
	#The text that gets displayed when the small image is hovered
	smallImageText = "Eterna | https://www.bisecthosting.com/eterna for 25% off!"
	#The buttons to display on Discord
	buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "Eterna | %player% is currently lazy"
	#The seconds line of text under the app name
	state = "Eterna | Currently in the menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = "eterna"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Eterna | https://www.curseforge.com/minecraft/modpacks/eterna-fabric"
	#The Asset ID of the image to display as the small image
	smallImageKey = "cube"
	#The text that gets displayed when the small image is hovered
	smallImageText = "Eterna | https://www.bisecthosting.com/eterna for 25% off!"
	#The buttons to display on Discord
	buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "Eterna | %player% is looking for a server"
	#The second line of text under the app name
	state = "Searching for friends"
	#The Asset ID of the image to display as the large image
	largeImageKey = "eterna"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Eterna | https://www.curseforge.com/minecraft/modpacks/eterna-fabric"
	#The Asset ID of the image to display as the small image
	smallImageKey = "cube"
	#The text that gets displayed when the small image is hovered
	smallImageText = "Eterna | https://www.bisecthosting.com/eterna for 25% off!"
	#The buttons to display on Discord
	buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "Eterna | %player% is joining a game"
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID of the image to display as the large image
	largeImageKey = "eterna"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Eterna | https://www.curseforge.com/minecraft/modpacks/eterna-fabric"
	#The Asset ID of the image to display as the small image
	smallImageKey = "cube"
	#The text that gets displayed when the small image is hovered
	smallImageText = "Eterna | https://www.bisecthosting.com/eterna for 25% off!"
	#The buttons to display on Discord
	buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Eterna | Currently In %world%"
	#The second line of text under the app name
	state = "Eterna | Playing Singleplayer"
	#The Asset ID of the image to display as the large image
	largeImageKey = "eterna"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Eterna | https://www.curseforge.com/minecraft/modpacks/eterna-fabric"
	#The Asset ID of the image to display as the small image
	smallImageKey = "cube"
	#The text that gets displayed when the small image is hovered
	smallImageText = "Eterna | https://www.bisecthosting.com/eterna for 25% off!"
	#The buttons to display on Discord
	buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Eterna | Playing on %serverip% with %players% players"
	#The second line of text under the app name
	state = "Eterna | Playing online as %player%"
	#The Asset ID of the image to display as the large image
	largeImageKey = "eterna"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Eterna | https://www.curseforge.com/minecraft/modpacks/eterna-fabric"
	#The Asset ID of the image to display as the small image
	smallImageKey = "cube"
	#The text that gets displayed when the small image is hovered
	smallImageText = "Eterna | https://www.bisecthosting.com/eterna for 25% off!"
	#The buttons to display on Discord
	buttons = []

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Playing Minecraft"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "eterna"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Eterna | https://www.curseforge.com/minecraft/modpacks/eterna-fabric"
	#The Asset ID of the image to display as the small image
	smallImageKey = "cube"
	#The text that gets displayed when the small image is hovered
	smallImageText = "Eterna | https://www.bisecthosting.com/eterna for 25% off!"
	#The buttons to display on Discord
	buttons = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "%player% is in The Overworld"
		state = ""
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = "%player% is in The Nether"
		state = ""
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = "%player% is in The End"
		state = ""
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

